os: linux
language: ruby
arch: arm64
compiler: arm-linux-gnueabihf-g++-6
after_success:
- echo -e "!!!!!!after success executed!!!!!!"
after_failure:
- echo -e "!!!!!!!after failure executed!!!!!!!!"
